---
- name: Ensure presense of {{ cert_generator_catalog_destination }}
  ansible.builtin.file:
    path: "{{ cert_generator_catalog_destination }}"
    state: directory
    mode: "0755"

- name: Check presence of key file
  ansible.builtin.stat:
    path: "{{ cert_generator_catalog_destination }}/{{ cert_generator_key_name }}"
  register: cert_generator_key_file

- name: Certificate generation
  when: cert_generator_overrite_existed or not cert_generator_key_file.stat.exists
  block:
    - name: Generating openssl config for unattended creating of the certificate
      ansible.builtin.template:
        src: openssl_config.j2
        dest: /tmp/tmp_openssl.conf
        mode: "0755"

    - name: Creation of cert
      ansible.builtin.shell:
        cmd: |
          /bin/openssl req -new -newkey rsa:{{ cert_generator_key_lenght }} -x509 -sha256 -days {{ cert_generator_days }} \
          -nodes -out {{ cert_generator_catalog_destination }}/{{ cert_generator_cert_name }} \
          -keyout {{ cert_generator_catalog_destination }}/{{ cert_generator_key_name }} -config /tmp/tmp_openssl.conf \
      register: cert_creating
      changed_when: cert_creating.rc != 0

    - name: Set up right permission to key file
      ansible.builtin.file:
        path: "{{ cert_generator_catalog_destination }}/{{ cert_generator_key_name }}"
        mode: "0400"
