---
- name: Ensure Ansible packages for SELinux are installed
  ansible.builtin.dnf:
    name: python3-libselinux
    state: present

- name: Completely disable SELinux
  ansible.posix.selinux: # NOTE: before use of ansible linter, it's required to be launched: ansible-galaxy collection install ansible.posix
    state: disabled
