---
- name: Configure the Server
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    mode: "0755"
  notify: Systemd nginx restart

- name: Configure the site config
  ansible.builtin.template:
    src: webapp.j2
    dest: /etc/nginx/conf.d/webapp.conf
    mode: "0755"
  notify: Systemd nginx restart
