---
- name: Installing Nginx
  ansible.builtin.include_tasks: install.yml
  tags:
    - nginx
    - nginx-intall

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - nginx
    - nginx-config

- name: SystemD
  ansible.builtin.include_tasks: systemd.yml
  tags:
    - nginx
    - nginx-systemd
