- name: Generate systemd unit
  template:
    src: systemd.unit.j2
    dest: /etc/systemd/system/nginx.service
  register: nginx_systemd

- name: Ensuring enabled state of the service
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Ensuring the service is noticed due to configs have changed
  systemd:
    name: nginx
    state: reloaded
  when: (nginx_server_config is defined and nginx_server_config.changed) or (nginx_site_config is defined and nginx_site_config.changed)

- name: Ensuring the service is noticed due to systemd unit have changed
  systemd:
    name: nginx
    state: restarted
  when: nginx_systemd.changed
