---
- name: Generate systemd unit
  ansible.builtin.template:
    src: systemd.unit.j2
    dest: /etc/systemd/system/nginx.service
    mode: "0755"
  notify: Systemd nginx restart

- name: Ensuring enabled state of the service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Ensuring the service is noticed due to configs have changed
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  notify: Systemd nginx restart
