repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: check-json
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args:
    - --fix=lf

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    exclude: provision/.*$
    args:
    - --autofix
    - --indent
    - '2'
  - id: pretty-format-rust
    args:
    - --autofix
    - --manifest-path
    - webapp-rust/Cargo.toml
  - id: pretty-format-golang
    args:
    - --autofix

- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v24.9.2
  hooks:
  - id: ansible-lint
    files: provision/.*$
    always_run: false
    args:
    - --fix
    - provision/
