---
- name: Install EPEL repo
  dnf:
    name: epel-release
    state: present

- name: Import EPEL GPG key
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
