---
- name: Install EPEL repo
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
