---
- name: Check webapp file presence
  ansible.builtin.stat:
    path: "{{ webapp_file_name_path }}"
  register: webapp_file

- name: Build the artifact
  block:
    - name: Launch Gradle wrapper
      ansible.builtin.command: "{{ webapp_build_tool }}/gradlew -b {{ webapp_build_tool }}/build.gradle build"
      register: app_build
      changed_when: app_build.rc != 0

    - name: Ensure needed directory
      ansible.builtin.file:
        path: "{{ webapp_catalog_location }}"
        state: directory
        mode: "0755"

    - name: Copy the artifact to right place
      ansible.builtin.copy:
        src: "{{ webapp_build_tool }}/build/libs/{{ webapp_base_filename }}"
        dest: "{{ webapp_file_name_path }}"
        mode: "0644"
      notify: Systemd webapp-spring-boot restart
