---
- name: Build the artifact
  ansible.builtin.include_tasks: build.yml
  tags:
    - webapp
    - webapp-build

- name: Systemd settings
  ansible.builtin.include_tasks: systemd.yml
  tags:
    - webapp
    - webapp-systemd
