---

- name: Generate systemd unit
  template:
    src: systemd-unit.j2
    dest: /etc/systemd/system/webapp.service
  register: webapp_systemd

- name: Ensuring enabled state of the service
  systemd:
    name: webapp
    enabled: yes
    state: started

- name: Ensuring the service is noticed due to systemd unit have changed
  systemd:
    name: nginx
    state: restarted
  when: webapp_systemd.changed
 