---
- name: Generate systemd unit
  ansible.builtin.template:
    src: systemd-unit.j2
    dest: /etc/systemd/system/webapp.service
    mode: "0755"
  notify: Systemd nginx restart

- name: Ensuring enabled state of the service
  ansible.builtin.systemd:
    name: webapp
    enabled: true
    state: started
