---
- name: Generate systemd unit
  ansible.builtin.template:
    src: systemd-unit.j2
    dest: /etc/systemd/system/webapp-spring-boot.service
    mode: "0755"
  notify: Systemd webapp-spring-boot restart

- name: Ensuring enabled state of the service
  ansible.builtin.systemd:
    name: webapp-spring-boot
    enabled: true
    state: started
