---
cert_generator_catalog_destination: /etc/ssl/certs

cert_generator_key_name: MyKey.key
cert_generator_key_lenght: 4096

cert_generator_cert_name: MyCert.crt
cert_generator_days: 365

cert_generator_overrite_existed: false

cert_generator_config:
  C: RU
  ST: MSK
  L: MSK
  O: SomeCompany
  OU: Sales
  CN: User1234
  emailAddress: user1234@gmail.com
